version: '3'

services:

  ##? db container build seperately in ./db/compose.yml

  # db:
  #   container_name: ${IMAGE_BASE_NAME}-db
  #   image: postgres:15
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-postgres}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
  #     PGDATA: /data/postgres
  #     POSTGRES_DB: ${DB_COLLECTION}
  #   volumes:
  #      - ./db/postgres:/data/postgres
  #   ports:
  #     - "${DB_PORT}:5432"
  #   networks:
  #     - this

  backend:
    container_name: ${IMAGE_BASE_NAME}-backend
    image: ${IMAGE_BASE_NAME}-backend:latest # rename ALL 'cutefruit-kypn' to a unique name 
    restart: unless-stopped
    env_file:
      - .env
    build: 
      context: ./
      dockerfile: ./Dockerfile.backend
    # ports: # expose this if you're not using a proxy
    #   - 3001:3001
    networks:
      - this
      - proxy # comment out if not using proxy

  frontend:
    container_name: ${IMAGE_BASE_NAME}-frontend
    image: ${IMAGE_BASE_NAME}-frontend:latest # rename ALL 'cutefruit-kypn' to a unique name 
    restart: unless-stopped
    env_file:
      - .env
    build: 
      context: ./
      dockerfile: ./Dockerfile.frontend
    # ports: # expose this if you're not using a proxy
    #   - 3000:3000
    networks:
      - this
      - proxy # comment out if not using proxy
    # depends_on:
    #   - db
    #   # - backend

networks:    
  ## network first built in ./db/compose.yml, then linked with 'external: true' here
  this:
    name: ${IMAGE_BASE_NAME}-network
    driver: bridge  
    external: true # external because the db container will first create the network
  proxy:  # comment out if not using proxy
    name: nginx-prox-mgmt-3_default # your unique named proxy network
    driver: bridge
    external: true