services:

  ## db container build seperately in ./db/compose.yml
  # db:
  #   container_name: ${IMAGE_BASE_NAME}-db
  #   image: postgres:16
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-postgres}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
  #     PGDATA: /data/postgres
  #     POSTGRES_DB: ${DB_COLLECTION}
  #   volumes:
  #       - ./db/data-postgres:/data/postgres
  #   # ports:
  #   #   - "${DB_PORT}:5432"
  #   networks:
  #     - this

  backend:
    container_name: ${IMAGE_BASE_NAME}-backend
    image: ${IMAGE_BASE_NAME}-backend:latest # rename ALL 'cutefruit-kypn' to a unique name 
    restart: unless-stopped
    env_file:
      - .env
    build: 
      context: ./
      dockerfile: ./Dockerfile.backend
      args:
        PRODUCTION_PLATFORM: ${PRODUCTION_PLATFORM}
    ports: # expose this if you're not using a proxy
      - 8001:3001
    networks:
      - this
      # - proxy # TODO turn back on when using proxy
    # depends_on:
    #   - db

  frontend:
    container_name: ${IMAGE_BASE_NAME}-frontend
    image: ${IMAGE_BASE_NAME}-frontend:latest # rename ALL 'cutefruit-kypn' to a unique name 
    restart: unless-stopped
    env_file:
      - .env
    build: 
      context: ./
      # dockerfile: ./Dockerfile.frontend
      ## todo trying out optimization https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
      dockerfile: ./Dockerfile.frontend.standalone
      args:
        PRODUCTION_PLATFORM: ${PRODUCTION_PLATFORM}
    ports: # expose this if you're not using a proxy
      - 8000:3000
    networks:
      - this
      # - proxy # TODO turn back on when using proxy
    # depends_on:
    #   - db

networks:    
  ## network first built in ./db/compose.yml, then linked with 'external: true' here
  this:
    name: ${IMAGE_BASE_NAME}-network
    driver: bridge  
    # external: true 
  # proxy:  # TODO turn back on when using proxy
  #   name: nginx-prox-mgmt-3_default # whatever proxy container network
  #   driver: bridge
  #   external: true