ARG PRODUCTION_PLATFORM
FROM --platform=$PRODUCTION_PLATFORM node:21-alpine AS builder
# FROM node:18-alpine
WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY . .
COPY .env.prod ./.env
RUN yarn install --frozen-lockfile
# For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended
RUN yarn add sharp
RUN yarn generate
RUN yarn build
RUN yarn next telemetry disable
# RUN find ./

FROM builder as runner
WORKDIR /app

COPY --from=builder /app/package.json .
COPY --from=builder /app/yarn.lock .
COPY --from=builder /app/.env .

## todo we may not need this as needed modules should be in .next folder
COPY --from=builder /app/.keystone ./.keystone
COPY --from=builder /app/schema.prisma ./schema.prisma
COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/public ./public
## todo we may not need this as needed modules should be in .next folder
## https://nextjs.org/docs/app/api-reference/next-config-js/output#automatically-copying-traced-files-experimental
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next

EXPOSE $WEB_PORT
ENV NODE_ENV production

CMD ["pnpm", "start"]