FROM --platform=linux/amd64 node:18-alpine

WORKDIR /app

# # Install dependencies based on the preferred package manager
# COPY package.json yarn.lock* ./
# # KEYSTONE file required for post install scripts
# COPY keystone.ts schema.* auth.ts ./
COPY . .

RUN yarn install
RUN yarn generate
RUN yarn build
RUN yarn next telemetry disable

EXPOSE 3000
ENV NODE_ENV production
ENV PORT 3000

CMD ["yarn", "start"]