version: '3'

services:

  backend:
    container_name: kpyn-test-backend
    image: kpyn-test:latest # rename ALL 'kpyn-test' to a unique name 
    restart: unless-stopped
    build: .
    ports: # expose this if you're not using a proxy
      - 8881:3000
    networks:
      - this
      # - proxy # TODO turn back on when using proxy
    # depends_on:
    #   - db

networks:    
  this:
    name: kpyn-test-network
    driver: bridge   
  # proxy:  # TODO turn back on when using proxy
  #   name: nginx-prox-mgmt-3_default # whatever proxy container network
  #   driver: bridge
  #   external: true