services:
  db:
    container_name: ${IMAGE_BASE_NAME}-db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_COLLECTION}
    volumes:
        - ./data-postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    networks:
      - this

networks:    
  this:
    name: ${IMAGE_BASE_NAME}-network
    driver: bridge  