const SITE_TITLE = process.env.NEXT_PUBLIC_SITE_TITLE
const SITE_DESCRIPTION = process.env.NEXT_PUBLIC_SITE_DESCRIPTION
const ADMIN_EMAIL_ADDRESS = process.env.NEXT_PUBLIC_ADMIN_EMAIL_ADDRESS
const ASSET_REPO = process.env.NEXT_PUBLIC_ASSET_REPO
const SITE_URI = process.env.NEXT_PUBLIC_SITE_URI

export const envvars = {
  SITE_TITLE,
  SITE_DESCRIPTION,
  ADMIN_EMAIL_ADDRESS,
  ASSET_REPO,
  SITE_URI,
}